controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_customers_list:
    path: /customers
    controller: App\Controller\CustomerController::getCustomers
    methods: ['GET']

app_customer_details:
    path: /customers/{customerId}
    controller: App\Controller\CustomerController::getCustomer
    methods: ['GET']
